name: Build Flutter APK
on:
  push:
    branches: [ master ]
  workflow_dispatch: # 网页手动一键打包

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 拉取完整仓库代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 配置Flutter环境（改成你项目实际版本）
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'

      # 安装Android编译SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # 缓存依赖，加速重复打包
      - name: Cache Flutter & Gradle deps
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            ~/.gradle
            flutter-app/.dart_tool
            flutter-app/build
          key: flutter-${{ hashFiles('flutter-app/pubspec.yaml') }}

      # 切换flutter-app目录，通过环境变量指定国内pub源（无报错方案）
      - name: Install dependencies
        working-directory: ./flutter-app
        env:
          PUB_HOSTED_URL: https://pub.flutter-io.cn
        run: flutter pub get

      # 编译Debug测试APK
      - name: Build Debug APK
        working-directory: ./flutter-app
        run: flutter build apk --debug --split-per-abi

      # 上传APK产物
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Flutter-Debug-APK
          path: flutter-app/build/app/outputs/flutter-apk/*.apk
